/*
 *          _     _
 *          \`\ /`/
 *           \ V /
 *           /. .\            Bunny Kernel for MIPS
 *          =\ T /=
 *           / ^ \
 *        {}/\\ //\
 *        __\ " " /__
 *   jgs (____/^\____)
 *   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
/*! 	 
 *   @author Matus Dekanek, Tomas Petrusek, Lubos Slovak, Jan Vesely
 *   @par "SVN Repository"
 *   svn://aiya.ms.mff.cuni.cz/osy0809-depeslve
 *   
 *   @version $Id$
 *   @note
 *   Semestral work for Operating Systems course at MFF UK \n
 *   http://dsrg.mff.cuni.cz/~ceres/sch/osy/main.php
 *   
 *   @date 2008-2009
 */

/*!
 * @file 
 * @brief Register frame offsets.
 *
 * Taken from Kalisto, generated by script gen_offset.sh.
 */
/*
 * 
 *
 * Stack frame offsets.
 *
 * Do not modify. This file was generated by gen_offset.sh
 * from gen_offset.c.
 *
 */
#pragma once

#define REGS_OFFSET_ZERO 0
#define REGS_OFFSET_AT 4
#define REGS_OFFSET_V0 8
#define REGS_OFFSET_V1 12
#define REGS_OFFSET_A0 16
#define REGS_OFFSET_A1 20
#define REGS_OFFSET_A2 24
#define REGS_OFFSET_A3 28
#define REGS_OFFSET_T0 32
#define REGS_OFFSET_T1 36
#define REGS_OFFSET_T2 40
#define REGS_OFFSET_T3 44
#define REGS_OFFSET_T4 48
#define REGS_OFFSET_T5 52
#define REGS_OFFSET_T6 56
#define REGS_OFFSET_T7 60
#define REGS_OFFSET_T8 64
#define REGS_OFFSET_T9 68
#define REGS_OFFSET_S0 72
#define REGS_OFFSET_S1 76
#define REGS_OFFSET_S2 80
#define REGS_OFFSET_S3 84
#define REGS_OFFSET_S4 88
#define REGS_OFFSET_S5 92
#define REGS_OFFSET_S6 96
#define REGS_OFFSET_S7 100
#define REGS_OFFSET_K0 104
#define REGS_OFFSET_K1 108
#define REGS_OFFSET_GP 112
#define REGS_OFFSET_FP 116
#define REGS_OFFSET_SP 120
#define REGS_OFFSET_RA 124
#define REGS_OFFSET_HI 132
#define REGS_OFFSET_LO 128
#define REGS_OFFSET_EPC 136
#define REGS_OFFSET_CAUSE 140
#define REGS_OFFSET_BADVA 144
#define REGS_OFFSET_STATUS 148
#define CONTEXT_SIZE 152

